// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXmL70gbaSV3l62QsPIC2--HMtvdUUmQE',
    appId: '1:120252309377:web:0501eb00b4f3ce98a55280',
    messagingSenderId: '120252309377',
    projectId: 'vehicle-manager-73a2e',
    authDomain: 'vehicle-manager-73a2e.firebaseapp.com',
    storageBucket: 'vehicle-manager-73a2e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtXlX_JikI6d_Rj0G8leMPeRYlz75Y_RI',
    appId: '1:120252309377:android:5525a48fb34e318ea55280',
    messagingSenderId: '120252309377',
    projectId: 'vehicle-manager-73a2e',
    storageBucket: 'vehicle-manager-73a2e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUzFeIVqdCWM2ULfn-EVlnBAsaQizpLho',
    appId: '1:120252309377:ios:5dcdf46fd7b7f559a55280',
    messagingSenderId: '120252309377',
    projectId: 'vehicle-manager-73a2e',
    storageBucket: 'vehicle-manager-73a2e.firebasestorage.app',
    iosBundleId: 'com.example.vehicleManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUzFeIVqdCWM2ULfn-EVlnBAsaQizpLho',
    appId: '1:120252309377:ios:5dcdf46fd7b7f559a55280',
    messagingSenderId: '120252309377',
    projectId: 'vehicle-manager-73a2e',
    storageBucket: 'vehicle-manager-73a2e.firebasestorage.app',
    iosBundleId: 'com.example.vehicleManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXmL70gbaSV3l62QsPIC2--HMtvdUUmQE',
    appId: '1:120252309377:web:9bd65cf1410a4540a55280',
    messagingSenderId: '120252309377',
    projectId: 'vehicle-manager-73a2e',
    authDomain: 'vehicle-manager-73a2e.firebaseapp.com',
    storageBucket: 'vehicle-manager-73a2e.firebasestorage.app',
  );
}
